fixtures:
  repositories:
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    archive: 'https://github.com/nanliu/puppet-archive.git'
    staging: 'https://github.com/nanliu/puppet-staging.git'
    concat: 'https://github.com/theforeman/puppet-concat.git'
    datacat: 'https://github.com/richardc/puppet-datacat.git'
    java: 'https://github.com/bodeco/puppet-java.git'
    helper: 'https://github.com/bodeco/bodeco_module_helper.git'
  symlinks:
    tomcat: "#{source_dir}"
