language: ruby
script: "bundle exec rake travis"
rvm:
  - 1.9.3
env:
  - PUPPET_GEM_VERSION="~> 3.4.0"
  - PUPPET_GEM_VERSION=">= 3.0.0"
matrix:
  allow_failures:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION=">= 3.0.0"
notifications:
  email: false
